### ISSUE TITLE
로그인을 하지 않은 사용자의 독서기록시 처리여부

### ISSUE THREAD

**Issue by RunaUXLabs** [spaceyoung/notebook#1]
현재 업로드 된 기능에서는 로그인을 하지 않은 사용자도 도서를 검색할 수 있습니다.
검색기능 오픈은 해당 웹앱을 구경 온 사용자들의 기능 탐색에 많은 도움이 될 것이라고 봅니다.
이슈는 그 다음인데요,
**로그인 여부에 따라 내비게이션 가드를 구현해야 할 것 같습니다.**

아래는 로그인을 하지 않은 사용자가 독서기록을 할 때의 alert 입니다.
1. 로그인을 하지 않은 사용자가 책을 검색
2. 검색 기록에서 원하는 책을 찾아 [기록하기]버튼 클릭(1차)
3. 날짜 및 독서 범위 입력 후 [기록하기]버튼 클릭(2차)
4. alert 출력

![2024-02-23_152805](https://github.com/spaceyoung/notebook/assets/73094198/b19df542-1794-40aa-9ffe-fd7e407dadfc)

아래는 로그인을 한 사용자가 독서기록을 하면 바로 나의기록으로 잘 넘어오는 화면입니다.
![2024-02-23_153059](https://github.com/spaceyoung/notebook/assets/73094198/2afee804-b193-434a-826a-f21da9e3fa7c)

다음 버전 릴리즈 때 반영이 될 수 있도록, 가능한 다양한 케이스를 적어봅니다.
- 현재 alert에서 비로그인사용자는 기록서비스를 이용할 수 없다고 안내하는 방법
- 비로그인 사용자에게는 [기록하기] 버튼을 감추는 방법
- 검색화면에서 [기록하기] (1차)버튼은 언제나 보이되,  비로그인 사용자가 클릭시 로그인화면으로 리디렉션 시키기

*[기록하기]버튼이 두 번이나 나와서 2차에 나오는 [기록하기]버튼은 [저장]으로 바꾸는 것도 좋을 것 같습니다.

**Comment by spaceyoung** [comment]
### Release v0.2.1에서 해당 이슈가 해결되었습니다!

ca9b6181a1f0fb7f68b76abd29f4f1425d7b5030

이제 **로그인을 하지 않은 사용자**가 **독서 기록을 요청**할 시, **로그인 화면으로 이동을 유도하는 모달창**이 생성됩니다.

곧바로 로그인 화면으로 이동하는 것보다는 사용자에게 안내와 함께 선택지를 제공하는 방법이 사용성 측면에서 낫다고 생각해 모달창을 거쳐가도록 기능을 추가했습니다.
<br>

![non-login-modal](https://github.com/spaceyoung/notebook/assets/154400292/2d069337-af2f-4d74-bda7-f84d2c28e67b)
